# Generated by Django 4.0.1 on 2022-01-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jacket',
            options={'ordering': ['time_create', 'name'], 'verbose_name': 'Классический Джакет', 'verbose_name_plural': 'Классические Джакеты'},
        ),
        migrations.AddField(
            model_name='jacket',
            name='photo',
            field=models.ImageField(default='./images/jacket.jpeg', upload_to='./images/Jackets/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='jacket',
            name='time_create',
            field=models.DateField(default='2022-01-28'),
        ),
        migrations.AddField(
            model_name='jacket',
            name='time_update',
            field=models.DateTimeField(default='2022-01-28'),
        ),
    ]
