# Generated by Django 4.0.1 on 2022-01-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0002_alter_jacket_options_jacket_photo_jacket_time_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jacket',
            name='time_update',
        ),
        migrations.AlterField(
            model_name='jacket',
            name='time_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
