# Generated by Django 4.0.1 on 2022-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0003_remove_jacket_time_update_alter_jacket_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
