# Generated by Django 4.0.1 on 2022-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0004_jacket_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='name2',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
