# Generated by Django 4.0.1 on 2022-01-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0005_jacket_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jacket',
            name='name2',
        ),
    ]
