# Generated by Django 4.0.1 on 2022-01-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0006_remove_jacket_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jacket',
            name='photo',
            field=models.ImageField(default='images/jacket.jpeg', upload_to='images/Jackets/%Y/%m/%d/'),
        ),
    ]
